# Changes here will be overwritten by Copier
_commit: 1.0.2-17-gfa4b4e7
_src_path: gh:DiamondLightSource/python-copier-template
author_email: tom.cobb@diamond.ac.uk
author_name: Tom Cobb
component_owner: group:default/sscc
description: An expanded python-copier-template with all the options
distribution_name: dls-python-copier-template-example
docker: true
docs_type: sphinx
git_platform: github.com
github_org: DiamondLightSource
package_name: python_copier_template_example
repo_name: python-copier-template-example
