# Changes here will be overwritten by Copier
_commit: 5.0.1-1-gd220299
_src_path: https://github.com/DiamondLightSource/python-copier-template.git
author_email: tom.cobb@diamond.ac.uk
author_name: Tom Cobb
component_lifecycle: experimental
component_owner: group:default/daq
component_type: service
description: An expanded https://github.com/DiamondLightSource/python-copier-template
    to illustrate how it looks with all the options enabled.
distribution_name: dls-python-copier-template-example
docker: true
docker_debug: true
docs_type: sphinx
git_platform: github.com
github_org: DiamondLightSource
package_name: python_copier_template_example
pypi: true
repo_name: python-copier-template-example
strict_typing: true
type_checker: pyright
