# Changes here will be overwritten by Copier
_commit: 2.0.2-10-g61bc692
_src_path: gh:DiamondLightSource/python-copier-template
author_email: tom.cobb@diamond.ac.uk
author_name: Tom Cobb
component_owner: group:default/sscc
description: An expanded https://github.com/DiamondLightSource/python-copier-template
    to illustrate how it looks with all the options enabled.
distribution_name: dls-python-copier-template-example
docker: true
docs_type: sphinx
git_platform: github.com
github_org: DiamondLightSource
package_name: python_copier_template_example
pypi: true
repo_name: python-copier-template-example
type_checker: pyright
